/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ADHARSH M NAIR
 */
public class Catalogue extends javax.swing.JFrame {

    /**
     * Creates new form Catalogue
     */
    public Catalogue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Account = new javax.swing.JButton();
        ViewCart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ONQTY = new javax.swing.JSpinner();
        ONATC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GHQTY = new javax.swing.JSpinner();
        GHATC = new javax.swing.JButton();
        onprice = new javax.swing.JLabel();
        ghprice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oilbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        oilprice = new javax.swing.JLabel();
        OATC = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SAPRICE = new javax.swing.JLabel();
        OilSpin = new javax.swing.JSpinner();
        SaltSpin = new javax.swing.JSpinner();
        SALTATC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Account.setText("Account");
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        ViewCart.setText("View Cart");
        ViewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCartActionPerformed(evt);
            }
        });

        jLabel1.setText("            Available Products");

        ONATC.setText("Add to Cart");
        ONATC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONATCActionPerformed(evt);
            }
        });

        jLabel3.setText("Onion  - 1Kg   ");

        jLabel4.setText("Washing Soap - 1kg ");

        GHATC.setText("Add to Cart");
        GHATC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GHATCActionPerformed(evt);
            }
        });

        onprice.setText("100.00");

        ghprice.setText("70.00");

        jLabel2.setText("Rs.");

        jLabel5.setText(" Rs.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("CATALOGUE");

        oilbl.setText("Sunflower Oil - 1ltr");

        jLabel8.setText("Rs.");

        oilprice.setText("70.00");

        OATC.setText("Add To Cart");
        OATC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OATCActionPerformed(evt);
            }
        });

        jLabel7.setText("Salt - 1kg");

        jLabel9.setText("Rs.");

        SAPRICE.setText("50.00");

        SALTATC.setText("Add To Cart");
        SALTATC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALTATCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(OilSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(oilbl)
                            .addComponent(jLabel4))
                        .addContainerGap(368, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Account)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewCart)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(SaltSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SALTATC))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(GHQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GHATC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ONQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(onprice))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(ONATC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ghprice)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(oilprice))
                                .addComponent(OATC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SAPRICE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account)
                    .addComponent(ViewCart))
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(onprice))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ONQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ONATC))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ghprice)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GHATC)
                    .addComponent(GHQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oilbl, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(oilprice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OATC)
                    .addComponent(OilSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(SAPRICE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaltSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALTATC))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        new Dashboard();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_AccountActionPerformed

    private void ViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCartActionPerformed
        // TODO add your handling code here:
        //new cart();
       new Cart().setVisible(true);
       dispose();
    }//GEN-LAST:event_ViewCartActionPerformed

    private void ONATCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONATCActionPerformed
        // TODO add your handling code here:
        try
{
 // create a mysql database connection
 String myDriver = "org.gjt.mm.mysql.Driver";
 String myUrl = "jdbc:mysql://localhost/shopping";
 Class.forName(myDriver);
 Connection conn = DriverManager.getConnection(myUrl, "root", "");
 String query = "INSERT INTO `cart`(`item`, `qty`, `price/unit`) VALUES (?,?,?)";
 PreparedStatement preparedStmt = conn.prepareStatement(query);
 preparedStmt.setString(1,jLabel3.getText());
 preparedStmt.setInt(2,(Integer)ONQTY.getValue());
 preparedStmt.setFloat(3,Float.parseFloat(onprice.getText()));
 preparedStmt.execute();
 JOptionPane.showMessageDialog(this, "ADDED TO CART");
}
         catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }

    }//GEN-LAST:event_ONATCActionPerformed

    private void GHATCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GHATCActionPerformed
         try
{
 // create a mysql database connection
 String myDriver = "org.gjt.mm.mysql.Driver";
 String myUrl = "jdbc:mysql://localhost/shopping";
 Class.forName(myDriver);
 Connection conn = DriverManager.getConnection(myUrl, "root", "");
 String query = "INSERT INTO `cart`(`item`, `qty`, `price/unit`) VALUES (?,?,?)";
 PreparedStatement preparedStmt = conn.prepareStatement(query);
 preparedStmt.setString(1,jLabel4.getText());
 preparedStmt.setInt(2,(Integer)GHQTY.getValue());
 preparedStmt.setFloat(3,Float.parseFloat(ghprice.getText()));
 preparedStmt.execute();
 JOptionPane.showMessageDialog(this, "ADDED TO CART");
}
         catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_GHATCActionPerformed

    private void OATCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OATCActionPerformed
        try
{
 // create a mysql database connection
 String myDriver = "org.gjt.mm.mysql.Driver";
 String myUrl = "jdbc:mysql://localhost/shopping";
 Class.forName(myDriver);
 Connection conn = DriverManager.getConnection(myUrl, "root", "");
 String query = "INSERT INTO `cart`(`item`, `qty`, `price/unit`) VALUES (?,?,?)";
 PreparedStatement preparedStmt = conn.prepareStatement(query);
 preparedStmt.setString(1,oilbl.getText());
 preparedStmt.setInt(2,(Integer)OilSpin.getValue());
 preparedStmt.setFloat(3,Float.parseFloat(oilprice.getText()));
 preparedStmt.execute();
 JOptionPane.showMessageDialog(this, "ADDED TO CART");
}
         catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_OATCActionPerformed

    private void SALTATCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALTATCActionPerformed
        try
{
 // create a mysql database connection
 String myDriver = "org.gjt.mm.mysql.Driver";
 String myUrl = "jdbc:mysql://localhost/shopping";
 Class.forName(myDriver);
 Connection conn = DriverManager.getConnection(myUrl, "root", "");
 String query = "INSERT INTO `cart`(`item`, `qty`, `price/unit`) VALUES (?,?,?)";
 PreparedStatement preparedStmt = conn.prepareStatement(query);
 preparedStmt.setString(1,jLabel7.getText());
 preparedStmt.setInt(2,(Integer)SaltSpin.getValue());
 preparedStmt.setFloat(3,Float.parseFloat(SAPRICE.getText()));
 preparedStmt.execute();
 JOptionPane.showMessageDialog(this, "ADDED TO CART");
}
         catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_SALTATCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton GHATC;
    private javax.swing.JSpinner GHQTY;
    private javax.swing.JButton OATC;
    private javax.swing.JButton ONATC;
    private javax.swing.JSpinner ONQTY;
    private javax.swing.JSpinner OilSpin;
    private javax.swing.JButton SALTATC;
    private javax.swing.JLabel SAPRICE;
    private javax.swing.JSpinner SaltSpin;
    private javax.swing.JButton ViewCart;
    private javax.swing.JLabel ghprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel oilbl;
    private javax.swing.JLabel oilprice;
    private javax.swing.JLabel onprice;
    // End of variables declaration//GEN-END:variables
}
